version: '3'
services:
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-api
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db